1322:0Traceback (most recent call last):
  File "/home/buildbot/sbox/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 293, in addCallbacks
    self._runCallbacks()
  File "/home/buildbot/sbox/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/buildbot/sbox/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 380, in callback
    self._startRunCallbacks(result)
  File "/home/buildbot/sbox/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 488, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/buildbot/sbox/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/buildbot/buildbot/master/buildbot/process/buildstep.py", line 867, in <lambda>
    d.addCallback(lambda res: self.commandComplete(cmd))
  File "/home/buildbot/buildbot/master/buildbot/steps/shell.py", line 336, in commandComplete
    ''.join(log.getChunks([STDERR], onlyText=True)))
  File "/home/buildbot/master/master.cfg", line 71, in string2list
    logging.error('DoStepIf:%s',DoStepIf)
exceptions.NameError: global name 'DoStepIf' is not defined
,